In [1]:
import pandas as pd

# 2 Series

In [2]:
# 生成一个Series

ser_obj = pd.Series(range(10, 20)) #默认索引是0-9
print(ser_obj) #打印输出会带有类型


0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64


In [3]:
print('-'*50)
# 获取数据
print(ser_obj.values)  #values实际是ndarray
print(type(ser_obj.values)) #类型是ndarray
# 获取索引
print(ser_obj.index)  #内部自带的类型--RangeIndex
ser_obj.dtype #数据类型

--------------------------------------------------
[10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=10, step=1)


dtype('int64')

In [4]:
print(ser_obj[0]) 
ser_obj[9] #
# 访问不存在的索引下标会报keyerror

10


np.int64(19)

In [5]:
print(ser_obj * 2)  #元素级乘法
print(ser_obj > 15) #返回一个bool序列

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [6]:
#字典变为series，索引是字典的key，value是字典的value，感受非默认索引

year_data = {2001: 17.8, 2005: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2)
print('-'*50)
print(ser_obj2.index)
print('-'*50)
print(ser_obj2[2001])
ser_obj2.values

2001    17.8
2005    20.1
2003    16.5
dtype: float64
--------------------------------------------------
Index([2001, 2005, 2003], dtype='int64')
--------------------------------------------------
17.8


array([17.8, 20.1, 16.5])

In [7]:
#有点鸡肋
print(ser_obj2.name) #Series名字
print(ser_obj2.index.name)  #索引名字
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year1'
print('-'*50)
print(ser_obj2.head())  #head默认显示前5行


None
None
--------------------------------------------------
year1
2001    17.8
2005    20.1
2003    16.5
Name: temp, dtype: float64


# 3 DataFrame

In [8]:
import numpy as np

# 通过ndarray构建DataFrame
t = pd.DataFrame(np.arange(12).reshape((3,4))) #默认索引是0-2
print(t)
print('-'*50)


   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
--------------------------------------------------


In [9]:
array = np.random.randn(5,4)
print(array)
print('-'*50)
df_obj = pd.DataFrame(array)
print(df_obj.head()) #默认显示前5行

[[ 0.5241058  -0.01993765  0.01877036 -0.9473285 ]
 [ 2.1252764   1.00898524  1.43299833 -0.92821824]
 [ 0.25196438 -0.26130499 -0.0862531   1.6304296 ]
 [ 0.33058288 -0.01437506  0.45315367  0.79231409]
 [-0.20780805  0.0771257  -0.31592541 -1.23583663]]
--------------------------------------------------
          0         1         2         3
0  0.524106 -0.019938  0.018770 -0.947329
1  2.125276  1.008985  1.432998 -0.928218
2  0.251964 -0.261305 -0.086253  1.630430
3  0.330583 -0.014375  0.453154  0.792314
4 -0.207808  0.077126 -0.315925 -1.235837


In [10]:
t.loc[0] #单独把某一行取出来,类型是series

0    0
1    1
2    2
3    3
Name: 0, dtype: int64

In [11]:
# 列表套字典  变df
d2 =[{"name" : "xiaohong" ,"age" :32,"tel" :10010},
     { "name": "xiaogang" ,"tel": 10000} ,
     {"name":"xiaowang" ,"age":22}]
df6=pd.DataFrame(d2)
print(df6) #缺失值会用NaN填充
print(type(df6.values)) #ndarray

       name   age      tel
0  xiaohong  32.0  10010.0
1  xiaogang   NaN  10000.0
2  xiaowang  22.0      NaN
<class 'numpy.ndarray'>


In [13]:
pd.Series(1, index=list(range(3,7)),dtype='float32')

3    1.0
4    1.0
5    1.0
6    1.0
dtype: float32

In [12]:
#df中不同列可以是不同的数据类型,同一列必须是一个数据类型
import pandas as pd
import numpy as np
dict_data = {'A': 1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([1,2,3,4],dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F': 'wangdao' }
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2)


   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao


In [15]:
print('-'*50)
print(df_obj2.index) #行索引,重点
#补课改变
# df_obj2.index[0]=2  不可以单独修改某个索引值
print(df_obj2.columns) #列索引，重点
df_obj2.dtypes #每一列的数据类型，重点

--------------------------------------------------
Index([0, 1, 2, 3], dtype='int64')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')


A            int64
B    datetime64[s]
C          float32
D            int32
E           object
F           object
dtype: object

In [14]:
# 感受日期,初始化df，设置行索引，列索引
dates = pd.date_range('20130101', periods=6) #默认freq='D'，即天
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print('-'*50)
print(df.index)


                   A         B         C         D
2013-01-01  0.269227 -1.598549  0.841282  1.921831
2013-01-02  0.128849  1.027913  0.894549  0.141593
2013-01-03 -0.408529 -0.483153 -0.651001 -0.645311
2013-01-04 -0.474281  0.858604 -0.775480  1.012280
2013-01-05  0.965321 -0.244701  0.272899 -0.283157
2013-01-06  0.761475  1.745497 -0.597230  0.277687
--------------------------------------------------
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [16]:
#取数据
print(df_obj2)
print('-'*50)
print(type(df_obj2))
print('-'*50)
#pd中使用索引名来取某一行，或者列
print(df_obj2['B'])
print('-'*50)
#把df的某一列取出来是series
print(type(df_obj2['B']))

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
--------------------------------------------------
0   2019-09-26
1   2019-09-26
2   2019-09-26
3   2019-09-26
Name: B, dtype: datetime64[s]
--------------------------------------------------
<class 'pandas.core.series.Series'>


In [17]:
#增加列数据，列名是自定义的
df_obj2['G'] = df_obj2['D'] + 4
print(df_obj2.head())

   A          B    C  D       E        F  G
0  1 2019-09-26  1.0  1  Python  wangdao  5
1  1 2019-09-26  1.0  2    Java  wangdao  6
2  1 2019-09-26  1.0  3     C++  wangdao  7
3  1 2019-09-26  1.0  4       C  wangdao  8


In [18]:
# 删除列
del(df_obj2['G'])
print(df_obj2.head())



   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
